---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-aws-karpenter
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: karpenter
                addonChartReleaseName: karpenter
                addonChartNamespace: karpenter
                addonChartVersion: v0.34.1
                # using oci repostory already configure in argocd
                # argocd repo add public.ecr.aws --type helm --name aws-public-ecr --enable-oci
                addonChartRepository: public.ecr.aws
              selector:
                matchExpressions:
                  - key: enable_karpenter
                    operator: In
                    values: ['true']
  template:
    metadata:
      name: addon-{{name}}-{{values.addonChart}}
    spec:
      project: default
      sources:
        - repoURL: '{{metadata.annotations.addons_repo_url}}'
          targetRevision: '{{metadata.annotations.addons_repo_revision}}'
          ref: values
        - repoURL: '{{metadata.annotation.addons_repo_url}}'
          targetRevision: HEAD
          chart: karpenter-resources
          helm:
            - valueFiles:
                - $values/{{metadata.annotations.addons_repo_basepath}}values/{{values.addonChart}}/values.yaml
        - chart: '{{values.addonChartRepositoryNamespace}}/{{values.addonChart}}'
          repoURL: '{{values.addonChartRepository}}'
          targetRevision: '{{values.addonChartVersion}}'
          helm:
            releaseName: '{{values.addonChartReleaseName}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{metadata.annotations.addons_repo_basepath}}values/{{values.addonChart}}/values.yaml
            values: |
              nodeClass:
                role: {{metadata.annotations.karpeneter_node_iam_role_arn}}
                name: {{metadata.annotations.aws_cluster_name}}-truemark-default
              clusterName: {{metadata.annotations.aws_cluster_name}}
              settings:
                clusterName: {{metadata.annotations.aws_cluster_name}}
                interruptionQueue: {{metadata.annotations.karpenter_sqs_queue_name}}
              serviceAccount:
                name: {{metadata.annotations.karpenter_service_account}}
                annotations:
                  eks.amazonaws.com/role-arn: {{metadata.annotations.karpenter_iam_role_arn}}
      destination:
        namespace: '{{values.addonChartNamespace}}'
        name: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.
