---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-aws-cert-manager
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
    - merge:
        mergeKeys: [server]
        generators:
          - clusters:
              values:
                addonChart: cert-manager
                addonChartVersion: v1.14.3
                addonChartRepository: https://charts.jetstack.io
              selector:
                matchExpressions:
                  - key: enable_cert_manager
                    operator: In
                    values: ['true']
                  - key: aws_cluster_name
                    operator: Exists
  template:
    metadata:
      name: addon-{{name}}-{{values.addonChart}}
    spec:
      project: default
      sources:
        - repoURL: '{{metadata.annotations.addons_repo_url}}'
          targetRevision: '{{metadata.annotations.addons_repo_revision}}'
          ref: values
        - chart: '{{values.addonChart}}'
          repoURL: '{{values.addonChartRepository}}'
          targetRevision: '{{values.addonChartVersion}}'
          helm:
            releaseName: '{{values.addonChart}}'
            ignoreMissingValueFiles: true
            valueFiles:
              - $values/{{metadata.annotations.addons_repo_basepath}}values/{{values.addonChart}}/values.yaml
            values: |
              {{- if ge (split .Values.certManagerChartVersion "." | index 1 | int) 15 }}
              crds:
                enabled: true
                keep: true
              {{- else }}
              installCRDS: true
              {{- end }}
              serviceAccount:
                name: {{metadata.annotations.cert_manager_service_account}}
                annotations:
                  eks.amazonaws.com/role-arn: {{metadata.annotations.cert_manager_iam_role_arn}}
          # fileParameters:
          #  - name:
          #    path:
          # parameters
          # values
          # valuesObject
      destination:
        namespace: '{{metadata.annotations.cert_manager_namespace}}'
        name: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.
